package sqlc

import (
	"testing"

	"github.com/arllen133/sqlc/clause"
	"github.com/stretchr/testify/assert"
)

func TestSchemaInterface(t *testing.T) {
	// Test that Schema interface is properly defined
	// This is a compile-time verification

	t.Run("Schema interface has required methods", func(t *testing.T) {
		// Verify that Schema interface exists and can be used as a type constraint
		// The actual schema implementations are generated by orm-gen
		// This test just ensures the interface is well-defined
		type schemaCheck interface {
			TableName() string
			SelectColumns() []string
			AutoIncrement() bool
		}

		// Schema interface should be compatible with schemaCheck
		var _ schemaCheck = (Schema[any])(nil)
	})
}

func TestPKStruct(t *testing.T) {
	t.Run("PK struct fields", func(t *testing.T) {
		pk := PK{
			Column: clause.Column{Name: "id"},
			Value:  int64(42),
		}

		assert.Equal(t, "id", pk.Column.Name)
		assert.Equal(t, int64(42), pk.Value)
	})
}
